[package]
name = "mockbob"
version = "3.0.0"
authors = ["j-brn <me@jbrn.eu>"]
edition = "2018"

[features]
clipboard = ["copypasta-ext"]

[dependencies]
mockbob-core = { path = "mockbob-core" }
structopt = "0.3"
copypasta-ext = { version = "0.3", optional = true }
