name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        sudo apt-get install -y xorg-dev
        cargo build
    - name: Run tests
      run: |
        sudo apt-get install -y xorg-dev
        cargo test --all
